[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
[project]
name = "libml_URLPhishing"
authors = [
  { name="Shantnav Agarwal", email="shantnavagarwal@gmail.com" },
]
description = "Library to download and process data for the URL phishing project"
readme = "ReadMe.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: Apache License",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/REMLA24-TEAM-15/libml"
Issues = "https://github.com/REMLA24-TEAM-15/libml/issues"