---
name: Release
on:
  push:
    tags: ["v[0-9]+.[0-9]+.[0-9]+"]
jobs:
  # Build the documentation and upload the static HTML files as an artifact.
  build:
    runs-on: ubuntu-latest
    env:
      KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
      KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # ADJUST THIS: install all dependencies (including pdoc)
      - run: pip install -r requirements.txt
      - run: pip install pdoc3
      # ADJUST THIS: build your documentation into docs/.
      # We use a custom build script for pdoc itself, ideally you just run `pdoc -o docs/ ...` here.
      - run: pdoc -o docs/ libml

      - uses: actions/upload-pages-artifact@v3
        with:
          path: docs/

  # Deploy the artifact to GitHub pages.
  # This is a separate job so that only actions/deploy-pages has the necessary permissions.
  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4

#  pypi-publish:
#    name: Upload release to PyPI
#    runs-on: ubuntu-latest
#    environment:
#      name: pypi
#      url: https://test.pypi.org/p/libml-URLPhishing
#    permissions:
#      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
#    steps:
#      # retrieve your distributions here
#      - name: Publish package distributions to PyPI
#        uses: pypa/gh-action-pypi-publish@release/v1