---
name: Release
on:
  push:
    tags: ["v[0-9]+.[0-9]+.[0-9]+"]
  workflow_dispatch:
jobs:
  # Build the documentation and upload the static HTML files as an artifact.
  build:
    runs-on: ubuntu-latest
    env:
      KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
      KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}
      name: pypi
      url: https://test.pypi.org/p/libml-URLPhishing
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # ADJUST THIS: install all dependencies (including pdoc)
      - run: pip install poetry

# Install all dependencies (including pdoc3) using Poetry
      - run: poetry install

# Ensure Poetry's environment is correctly set up
      - run: poetry run pip install pdoc3

# Build the package
      - run: poetry build

# Install the built package
      - run: pip install dist/*.whl

# Build your documentation into docs/
      - run: poetry run pdoc --html -o docs/ libml
      - uses: actions/upload-pages-artifact@v3
        with:
          path: docs/libml/
      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository-url: https://test.pypi.org/legacy/

  # Deploy the artifact to GitHub pages.
  # This is a separate job so that only actions/deploy-pages has the necessary permissions.
  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4


